"""
analysis.strategies.base

Base strategy interface.

Strategies convert market observations into trading intent.

A Strategy:
- reads StrategyContext
- produces Signals

A Strategy does NOT:
- execute orders
- manage portfolio state
- calculate commissions
- access broker internals
- modify market data
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from analysis.engine.models.context import StrategyContext
from analysis.engine.models.signal import Signal


class Strategy(ABC):
    """
    Abstract base class for all trading strategies.

    Every strategy in Research Wing must implement
    the `on()` method.

    The Backtester calls this method once per
    market event.
    """

    name: str = "UnnamedStrategy"


    def __init__(
        self,
        *,
        name: str | None = None,
    ) -> None:
        """
        Initialize strategy metadata.

        Parameters
        ----------
        name:
            Optional custom strategy name.
        """

        if name is not None:
            self.name = name



    @abstractmethod
    def on(
        self,
        context: StrategyContext,
    ) -> Signal | None:
        """
        Process a market event.

        Parameters
        ----------
        context:
            Read-only snapshot of current market state.

        Returns
        -------
        Signal | None:
            Trading intent generated by the strategy.

            Returning None means:
            no decision this timestep.

            Returning HOLD means:
            explicitly maintain current exposure.
        """

        raise NotImplementedError



    def reset(self) -> None:
        """
        Reset strategy state.

        Stateful strategies may override this.

        Examples:
        - ML models
        - reinforcement learning agents
        - adaptive strategies

        Stateless strategies can ignore it.
        """

        pass



    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}"
            f"(name={self.name})"
        )